<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ToNcErrorCode_Tests" Id="{eeee2df2-70e3-0b22-0bc5-56743421a8c2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ToNcErrorCode_Tests EXTENDS FB_TestSuite
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ConversionOfValidErrorCode();
]]></ST>
    </Implementation>
    <Method Name="ConversionOfValidErrorCode" Id="{7468ef5f-d38a-04ed-37df-1008d5c474e3}">
      <Declaration><![CDATA[METHOD ConversionOfValidErrorCode
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TcUnit.TEST('ConversionOfValidErrorCode');

AssertEquals_UDINT(
    Expected:=NcErrorCodes.CONTROLLER_ERROR_DRIVE_ADDRESS,
    Actual:=ToNcErrorCode(17730),
    Message:='Error conversion not correct.'
);

TcUnit.TEST_FINISHED();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>